// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnsayusQ5ULjWaT0iN1WdSpvTsB4V7vCU',
    appId: '1:849380564877:web:04a51ce2dfab700cdde7c4',
    messagingSenderId: '849380564877',
    projectId: 'sipwise-6b3a6',
    authDomain: 'sipwise-6b3a6.firebaseapp.com',
    storageBucket: 'sipwise-6b3a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8irl_DJR-RDlpQe1AwM6sgLdnbQLTy0I',
    appId: '1:849380564877:android:b87b7a34b28994f4dde7c4',
    messagingSenderId: '849380564877',
    projectId: 'sipwise-6b3a6',
    storageBucket: 'sipwise-6b3a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaRPunHNXKtp-wzV2ryLYMukcr4BEQCVU',
    appId: '1:849380564877:ios:62e8cc598c77cba3dde7c4',
    messagingSenderId: '849380564877',
    projectId: 'sipwise-6b3a6',
    storageBucket: 'sipwise-6b3a6.appspot.com',
    iosBundleId: 'com.example.wiseBean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaRPunHNXKtp-wzV2ryLYMukcr4BEQCVU',
    appId: '1:849380564877:ios:173cc135983bb7f4dde7c4',
    messagingSenderId: '849380564877',
    projectId: 'sipwise-6b3a6',
    storageBucket: 'sipwise-6b3a6.appspot.com',
    iosBundleId: 'com.example.wiseBean.RunnerTests',
  );
}
